##
## Modules
##

    modules.includes.required[relevant]=\
        apps/portal-search

##
## Test Batch
##

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]}

    #
    # Relevant
    #

    search.engine[relevant]=opensearch2

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
        (portal.acceptance == true) AND \
        (\
            (portal.suite.search.engine ~ elasticsearch7) OR \
            (portal.suite.search.engine ~ opensearch2)\
        )

    test.batch.run.property.query[functional-upgrade-tomcat*-mysql*-jdk8][relevant]=\
        (\
            (portal.suite.search.engine ~ elasticsearch7) OR \
            (portal.suite.search.engine ~ opensearch2)\
        ) AND \
        (testray.main.component.name ~ "Upgrades Search")

##
## Testray
##

    testray.main.component.name=Elasticsearch Impl