/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.search.experiences.blueprints.model.impl;

import com.liferay.search.experiences.blueprints.model.Blueprint;
import com.liferay.search.experiences.blueprints.service.BlueprintLocalServiceUtil;

/**
 * The extended model base implementation for the Blueprint service. Represents a row in the &quot;Blueprint&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BlueprintImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BlueprintImpl
 * @see Blueprint
 * @generated
 */
public abstract class BlueprintBaseImpl
	extends BlueprintModelImpl implements Blueprint {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a blueprint model instance should use the <code>Blueprint</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BlueprintLocalServiceUtil.addBlueprint(this);
		}
		else {
			BlueprintLocalServiceUtil.updateBlueprint(this);
		}
	}

}