/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.search.experiences.blueprints.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Element service. Represents a row in the &quot;Element&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.search.experiences.blueprints.model.impl.ElementModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.search.experiences.blueprints.model.impl.ElementImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Element
 * @generated
 */
@ProviderType
public interface ElementModel
	extends BaseModel<Element>, GroupedModel, LocalizedModel, MVCCModel,
			ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a element model instance should use the {@link Element} interface instead.
	 */

	/**
	 * Returns the primary key of this element.
	 *
	 * @return the primary key of this element
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this element.
	 *
	 * @param primaryKey the primary key of this element
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this element.
	 *
	 * @return the mvcc version of this element
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this element.
	 *
	 * @param mvccVersion the mvcc version of this element
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this element.
	 *
	 * @return the uuid of this element
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this element.
	 *
	 * @param uuid the uuid of this element
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the element ID of this element.
	 *
	 * @return the element ID of this element
	 */
	public long getElementId();

	/**
	 * Sets the element ID of this element.
	 *
	 * @param elementId the element ID of this element
	 */
	public void setElementId(long elementId);

	/**
	 * Returns the group ID of this element.
	 *
	 * @return the group ID of this element
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this element.
	 *
	 * @param groupId the group ID of this element
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this element.
	 *
	 * @return the company ID of this element
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this element.
	 *
	 * @param companyId the company ID of this element
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this element.
	 *
	 * @return the user ID of this element
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this element.
	 *
	 * @param userId the user ID of this element
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this element.
	 *
	 * @return the user uuid of this element
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this element.
	 *
	 * @param userUuid the user uuid of this element
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this element.
	 *
	 * @return the user name of this element
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this element.
	 *
	 * @param userName the user name of this element
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this element.
	 *
	 * @return the create date of this element
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this element.
	 *
	 * @param createDate the create date of this element
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this element.
	 *
	 * @return the modified date of this element
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this element.
	 *
	 * @param modifiedDate the modified date of this element
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this element.
	 *
	 * @return the status of this element
	 */
	public int getStatus();

	/**
	 * Sets the status of this element.
	 *
	 * @param status the status of this element
	 */
	public void setStatus(int status);

	/**
	 * Returns the title of this element.
	 *
	 * @return the title of this element
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this element in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this element
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this element in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this element. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this element in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this element
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this element in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this element
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this element.
	 *
	 * @return the locales and localized titles of this element
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this element.
	 *
	 * @param title the title of this element
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this element in the language.
	 *
	 * @param title the localized title of this element
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this element in the language, and sets the default locale.
	 *
	 * @param title the localized title of this element
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this element from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this element
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this element from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this element
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the description of this element.
	 *
	 * @return the description of this element
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this element in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this element
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this element in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this element. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this element in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this element
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this element in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this element
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this element.
	 *
	 * @return the locales and localized descriptions of this element
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this element.
	 *
	 * @param description the description of this element
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this element in the language.
	 *
	 * @param description the localized description of this element
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this element in the language, and sets the default locale.
	 *
	 * @param description the localized description of this element
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(
		String description, Locale locale, Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this element from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this element
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this element from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this element
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale);

	/**
	 * Returns the configuration of this element.
	 *
	 * @return the configuration of this element
	 */
	@AutoEscape
	public String getConfiguration();

	/**
	 * Sets the configuration of this element.
	 *
	 * @param configuration the configuration of this element
	 */
	public void setConfiguration(String configuration);

	/**
	 * Returns the hidden of this element.
	 *
	 * @return the hidden of this element
	 */
	public Boolean getHidden();

	/**
	 * Sets the hidden of this element.
	 *
	 * @param hidden the hidden of this element
	 */
	public void setHidden(Boolean hidden);

	/**
	 * Returns the read only of this element.
	 *
	 * @return the read only of this element
	 */
	public Boolean getReadOnly();

	/**
	 * Sets the read only of this element.
	 *
	 * @param readOnly the read only of this element
	 */
	public void setReadOnly(Boolean readOnly);

	/**
	 * Returns the type of this element.
	 *
	 * @return the type of this element
	 */
	public int getType();

	/**
	 * Sets the type of this element.
	 *
	 * @param type the type of this element
	 */
	public void setType(int type);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}